Fix codegen for modulo operation
There was a regression with the modulo operation. It turns out the srem
instruction does a signed division under the hood. Somewhat obvious
after the fact but easy to miss.

Example of previously broken script:

    BEGIN
    {
      @start = 0;
    }

    interval:ms:1
    {
      if ((@start % 200) == 0) {
        ++@start;
      }
    }

Compile error:

    Error: Unsupport signed division for DAG: 0x11d46d8: i64 = sdiv
    0x11d4d58, Constant:i64<200>Please convert to unsigned div/mod.
    ...